### ISSUE TITLE
American version crashes.

### ISSUE THREAD

**Issue by nanashi89** [leoetlino/project-restoration#119]
**Describe the bug**
Am on the American 1.1 eshop version. Loading the game crashes my 3DS, and I have to turn it off.

**To Reproduce**
Use patch 100, 101, or 110.
Rename code_faster_aim.bps to code.bps, and exheader_legacy.bin to exheader.bin.
Turn on 3DS.
Load Majora's Mask 1.1 USA.
3DS Crashes, and have to turn it off.
**Screenshots**

**Additional context**

**Comment by leoetlino** [comment]
Could you post a screenshot of the crash?

Also, are you using the Luma build that is mentioned in the instructions?

**Comment by nanashi89** [comment]
![20200322_123942](https://user-images.githubusercontent.com/23020427/77255052-1a663e80-6c3b-11ea-881a-7d05abb6febe.jpg)
![20200322_124004](https://user-images.githubusercontent.com/23020427/77255057-22be7980-6c3b-11ea-9d02-26657926e841.jpg)


And I am on 10.0.1 of Luma.

**Comment by leoetlino** [comment]
Okay, so the problem is that you aren't using the Luma version that is linked in the instructions (either on GitHub or at https://zora.re). The latest official version of Luma is bugged and will always crash when you try to use code patches. It also doesn't support BPS patches, so you must use the fork for now. Refer to https://zora.re for more information.
