### ISSUE TITLE
[Feature request] Some control remapping

### ISSUE THREAD

**Issue by DelusionalDeku** [leoetlino/project-restoration#120]
Since you use the ocarina some 20 times more often than you talk to Tatl, I think mapping the ocarina to d-pad right makes a _lot_ more sense.
If possible, I think it better to map Tatl to [L1], where it calls Tatl when the prompt is active but otherwise pulls up first-person mode (like in the original).

Would it be possible to change the Zora swimming controls to what Nerrel describes in his MM 3D video? As it is, it's a little awkward and I rarely use slow swimming. You have to either take you thumb off the control stick to press the d-pad, or hold [L1], which makes it difficult to also hold [L2] to target (which I often do since the camera doesn't follow you very well while swimming).

**Comment by leoetlino** [comment]
>Since you use the ocarina some 20 times more often than you talk to Tatl, I think mapping the ocarina to d-pad right makes a lot more sense.

>If possible, I think it better to map Tatl to [L1], where it calls Tatl when the prompt is active but otherwise pulls up first-person mode (like in the original).

Yes, mapping the ocarina to the D-Pad would probably make sense. WWHD has the waker on the D-Pad, too.

The problem is that we do not have enough buttons to map the Ocarina, the pictobox, X, Y, I, II, A, B and the masks without resorting to button modifiers (e.g. ZR+A for the ocarina, ZR+X for I, etc.) Moving Tatl to a second level mapping is a no-go, because there is no way to tell the player what they need to press. I'm also reluctant to move Tatl to a button that is already used for something else because I expect a lot of people (experienced players) to just want to ignore Tatl, and mapping Tatl to ZL for example would leave you unable to use the pictobox until you talk to Tatl or wait several seconds for the prompt to disappear...

>Would it be possible to change the Zora swimming controls to what Nerrel describes in his MM 3D video? As it is, it's a little awkward and I rarely use slow swimming. You have to either take you thumb off the control stick to press the d-pad, or hold [L1], which makes it difficult to also hold [L2] to target (which I often do since the camera doesn't follow you very well while swimming).

FWIW, this is not an issue on anything but the 3DS, which has an unfortunate button layout for ZL and ZR, but I do want to get this fixed since lots of users play on a real console.
  
That scheme would be very complicated to implement since a lot of functions tie Link's swimming state to the A button being held... How about moving the slow swim trigger to ZR? It's not used by anything while swimming.

**Comment by DelusionalDeku** [comment]
Would [R1] work for Tatl? Or a texture change so the Tatl prompt shows whatever shortcut it's tied to?
I think just changing [L1] to _toggle_ slow swimming would be a huge improvement

**Comment by leoetlino** [comment]
I ended up keeping Tatl on the D-Pad, because it turns out moving Tatl to another button would require a significant amount of work, and even more so for a touchscreen button. It would also require -- as you said -- a texture change, which is not something I can do for console since there are unfortunately no cross-platform tools for Grezzo's texture format. (And I don't have the time or motivation to write one...)

ZL is currently used to slow swim (temporarily), so I guess I'd need to move it to ZR first before I can put the toggle on ZL.
