### ISSUE TITLE
[Feature request] Ability to customize what is installed (enable/disable specific features)

### ISSUE THREAD

**Issue by JoshuaLindquist** [leoetlino/project-restoration#128]
It would be really nice to have the option to choose what changes are installed instead of all or nothing. I really want the controller setup with the new shortcuts, and some of the actual bug fixes sound great too. 

I generally like the changes that were made to the 3DS game - even the controversial ones - so the mod undoes features that I want. I'd love to disable those parts only.

**Comment by SamuelTheSuperb** [comment]
Agreed. A customizable installer would be great.

**Comment by leoetlino** [comment]
This would be quite complex to implement. Project Restoration works with a combination of C++ code and patches to the game executable, and the patch system uses Magikoopa, so you'd need something to generate the patch list dynamically and also set various defines (for the C++ parts).

But doing all that would only let you have compile-time options. Users would still have to build Project Restoration from source on their own.

Another option would be to add runtime options, i.e. build the code with everything enabled and allow specific features to be enabled or disabled by editing the patch binary with client side JavaScript. This still needs a fair amount of work and one problem is that you'd essentially need to regenerate the entire patch with JS because instruction patches cannot be safely done at runtime.

All in all, I don't think it's worth the complexity and the time to implement this, considering that most of the changes are either QoL improvements, optional additions or much less controversial than the original changes in MM3D.

If you need to disable specific features (or make any other changes you want), you can edit the source and build Project Restoration from source.
