### ISSUE TITLE
Attack Owl Statues to activate them instead of talking to them.

### ISSUE THREAD

**Issue by DeathWrench** [leoetlino/project-restoration#18]
I don't know if this is possible but it would be very nice addition

**Comment by leoetlino** [comment]
Why not, though I don't want this to *replace* talking, because that would make things a lot more complicated and require text editing.

**Comment by DeathWrench** [comment]
Yeah, I don't really think you would have to replace the talking, just make it so smacking it has the same effect.

**Comment by leoetlino** [comment]
Should be doable now that I understand how actors react to collision.

* [ ] determine which collision body is used for the owl statue
* [ ] find out how to detect a sword attack
* [ ] find out how to activate the statue -- shouldn't be too complicated, because there are at least two triggers: talking and proximity-based for the Clock Town statue

**Comment by leoetlino** [comment]
Adding this to milestone 1.5.0 as the RE work will likely be extremely useful for #3
