### ISSUE TITLE
D-Pad mask inputs just won't work for me

### ISSUE THREAD

**Issue by puhoy876** [leoetlino/project-restoration#186]
**Describe the bug**
For some reason the D-Pad mask inputs just don't seem to work, I'm really sorry if I'm not enabling something correctly but I just can't seem to find what I should do. The actual D-Pad is mapped correctly as Tatl notifications still work and I can see what she is saying. I will say that at this point I only have the Deku mask but I don't think that would make a difference.

**Additional context**
I want to say again I am really sorry if I am wasting anybody's time with this as I'm pretty new to all of this in general. I am playing on Canary 1970 but have also tried Nightly 1714. Thanks

**Comment by MrMaou** [comment]
Did you ever get this working? 
If not, I can try to help

**Comment by leoetlino** [comment]
I cannot reproduce your issue. I suspect your controller mappings are broken. In particular, you should check whether your R/ZR buttons are mapped correctly. Project Restoration distinguishes between ZR+Left/Right/etc. and Left/Right, and if your ZR button is always active (because of a mapping mistake) the mask shortcuts will not work.
