### ISSUE TITLE
[Feature request] add custom button mapping

### ISSUE THREAD

**Issue by kox-gaming** [leoetlino/project-restoration#203]
Please add a page in the settings menu, that allows you to change button mapping for the new features.

I'm using a nintendo 2ds so i can't use the zl & zr buttons, so i'd like an option to map those functions to other buttons like select+up or other combinations.

**Comment by PhlexPlexico** [comment]
Hey! There's actually a system module for exactly what you're asking for, and it can be game-dependent as well I believe. [rehid](https://github.com/hax0kartik/rehid) to remap your buttons so you can access those as needed as well, so long as the game registers them as active. There may need to be some workarounds done to enable the circlepad pro, since zl and zr is attached to that option in game as well.

**Comment by leoetlino** [comment]
Yeah, using rehid is the better option here. An in-game menu would be extremely complicated to implement and would never be as flexible as rehid.
