### ISSUE TITLE
Save Game - Quit Game

### ISSUE THREAD

**Issue by WishThePone95** [leoetlino/project-restoration#214]
There really isn't much detail that's needed as I'm sure the request is self-explanatory. I wanted to know if you could add the option to exit to the menu after saving to the owl statues, since otherwise you have to exit the game entirely and reopen it to go back to file select.

**Comment by leoetlino** [comment]
Unfortunately I'm going to have to reject this feature request because this is extremely risky to implement -- OoT3D added the ability to return to the title screen after saving and doing that alone led to several glitches (IIRC). That is not something I am willing to risk.

If you're playing on Citra, just use the "restart emulation" option and if you're playing on console, just stop the game and relaunch it.
