### ISSUE TITLE
large-screen / HD-HUD: No way to generate romfs/layout from this repo

### ISSUE THREAD

**Issue by patrickxia** [leoetlino/project-restoration#251]
I spent a while trying to change the layout for `large-screen` but realized that a way to generate the modified romfs layout files isn't present in the repo.

Is there a toolchain to create the patches or were those patched by hand? It actually seems like a major pain to even unpack/repack the GAR files.

**Comment by leoetlino** [comment]
Yes, I've written a library and some tools for manipulating GARs and the layout formats. Just created a repo for it: https://github.com/leoetlino/jktool

As you can see from the commit dates, I haven't been working on it since 2020, and it's not really maintained anymore. "It's dangerous to go alone, take [this](https://github.com/leoetlino/jktool)", but other than that you're on your own :) (PRs are still welcome though if you figure out more parts of the file formats or if you have bug fixes)

**Comment by leoetlino** [comment]
Also the "toolchain" is really clunky - the tools I posted only let you extract/repack the archives and serialise/deserialise the binary layout files to/from text. There is no graphical layout editor. That was on my todo list at some point but I've had to shelve those plans because of a lack of free time. :/
