### ISSUE TITLE
Skip Song of double time replay

### ISSUE THREAD

**Issue by bl4zerp** [leoetlino/project-restoration#36]
Is it possible to skip the replay after the second time its used in the same way that you made it to the elegy of emptiness and song of soaring?
It would help streamline some sidequests.

**Comment by leoetlino** [comment]
Unfortunately, I'm marking this as "wontfix". I think the SoDT is not played often enough to warrant the effort and skipping it would remove content from the game. Elegy of Emptiness replay is skipped because you are forced to play it many times in a row, and the Song of Soaring is also skipped because players will usually use it very often, and the replay doesn't add much since it's identical to the ocarina song. This isn't the case for the SoDT though, which isn't played *that* often and plays a unique melody during the replay.
