### ISSUE TITLE
Ice arrows usability in more areas + patching report

### ISSUE THREAD

**Issue by figo5211** [leoetlino/project-restoration#37]
Using a original NTSC-U cartdridge with no 1.1 update pre-installed, on New3DS console. Although I have the update installed, release 1.4.2 v101 or v110 patching don't seem to work, system's arm11 crashes and I have to reboot. v100 runs flawlessly, though.
I read somewhere that .bps may be superior than .ips, so that's why I have my concerns - plus, is in your v100 the Honey&Darling glitch patched?
Yes, I have checked the troubleshooting: maybe the problem is how the console starts to run the game, and I also installed the repository boot.firm on NAND via gm9. I'm just wondering if it's a real issue or not.
[Arm 11 Crash Dump.zip](https://github.com/leoetlino/project-restoration/files/3453558/Arm.11.Crash.Dump.zip)

Now, for an enhancement request. I cross-checked where you can use ice arrows in Original MM and MM3D after restoration patch. Well done, very faithful to the original! However... it could be more, case sensitive, I guess...?
There are places that the ice arrows could possibly work, but they strangely don't - even in the original: The Great Bay Coast (in contrast with Zora Cape Area, which is very weird), zora hall, Waterfall Rapids, Pirate's Fortress the swamps and woodfall, mountain village (winter and spring), Bomber's Hideout, Termina Field and Secret Shrine.
The Ice arrows work on Ikana Canyon and Stone Tower Temple.
It's nothing gamebreaking, I suppose, it's just awkward how some bodies of water simply don't freeze. On the other hand, it is faithful to the original, so that's fine too, I think...

Anyway, looking forward for future releases, you're doing an amazing job!

**Comment by leoetlino** [comment]
Yes, only v100 will work if you have a MM3D 1.0 cartridge even if you have the 1.1 update. For simplicity reasons, only MM3D 1.0 (v100) is supported; this patch will use 1.0 even if you have the 1.1 update (v101) installed or a MM3D 1.1 (v110) cartridge.

The new BPS patcher will refuse to apply incompatible patches and will crash (on purpose) instead of booting into a broken executable (which is what would happen with the IPS patcher).

That does mean the MM3D 1.0 glitches won't be patched, but I can patch game-breaking glitches manually if needed.

---

>Now, for an enhancement request. I cross-checked where you can use ice arrows in Original MM and MM3D after restoration patch. Well done, very faithful to the original! However... it could be more, case sensitive, I guess...?

The patch just reverts the entrance check Grezzo has *added* to the water code -- so ice arrows are expected to work exactly the same as in MM. It's the same code after all :P

Making them work in more areas would require more effort and more patches. Accepting this because I agree it's unclear why ice arrows wouldn't work in some locations. (FYI, ice arrows do work in Great Bay after defeating Gyorg; no idea if that's intended or not.)

**Comment by leoetlino** [comment]
Given the potential of introducing new glitches and the fact I'm running out of time for Project Restoration... unfortunately I cannot work on this. Thank you for your suggestion nonetheless.

**Comment by figo5211** [comment]
Glad you at least considered and tried to make it work. It's all right, as it's the same as the original. Looking forward to the final release.
