### ISSUE TITLE
Nerf Gyorg boss fight.

### ISSUE THREAD

**Issue by ShadeVortex** [leoetlino/project-restoration#75]
I always felt like Gyorg took too many hits to defeat, and since you have to do the second phase of the fight in 3D, the first phase especially feels too long. Actually, I'd prefer we do away with the second phase altogether, because it's a dumb change imo (adds tedium and RNG to the fight), but it'd be less work to just change the hits required to take down the first phase. It's not a hard fight, it's just long and tedious. It feels like every other boss fight takes less time, even Twinmold.

**Comment by MrManMain** [comment]
Honestly, I think the second phase is nice to have. Gyorg felt like an insignificant boss fight in the original (even without the Fierce Deity's Mask) so to have this extra phase makes the fight more climatic, I guess? Dunno what better word to use lol. The amount of hits needed to fight him in Phase 2 as Zora Link didn't feel as off as old 3d Twinmold and by getting good at swimming and hitting those mines, I was eventually able to beat him fairly quickly during his second phase.

The only thing I would really "nerf" is to find a way to make the Fierce Deity's Mask useful again in this fight as because of the platform collapsing during Phase 2, it takes too long to kill him with that mask and thus you have to go back to using the Zora Mask. Maybe the platform could be lowered slightly more slowly (unless it's tied to an animation) or maybe the Fierce Deity's Mask could be buffed in some way?

It may be possible that this change was intentional so that the second phase doesn't go to waste but the only way the fight can be nerfed without messing too much with the new design is an answer that's tied with the Fierce Deity's Mask imo. Currently, the Fierce Deity's Mask acts as a way to lower his health during the second phase and to breeze through the first phase (unless it's actually possible to kill Gyorg in the second phase as Fierce Deity Link?). Some could see it as taking away choice (which is understandable considering everything this remake has done) but it's also possible to see it as making the boss fight too trivial.

I'm not really advocating for this fight to change too much as, to me, the eye is enough. I was moreso just brainstorming and thinking of ideas to keep the spirit of the new fight without trivialising it. I hope I don't sound rude >.<

**Comment by leoetlino** [comment]
Yeah, I personally don't feel the need to nerf Gyorg any further. It is already indirectly nerfed by the more potent Inverted Song of Time and by the fact that the player can fast swim as Zora Link for as long as they want and they're likely more used to the controls now that fast swim is the default.

I don't think making the platform sink slower would solve the problem -- unless the sinking duration is significantly increased, which is obviously not a possibility. Fwiw, you can already kind of beat Gyorg during phase 2 without using the Zora mask by making ice platforms with ice arrows, and shooting at Gyorg with arrows. Or with sword beams, but I guess it would be difficult to defeat it before the ice melts...

Closing this for now.
