### ISSUE TITLE
[Feature request] Swap R L to ZR ZL

### ISSUE THREAD

**Issue by Justeego** [leoetlino/project-restoration#90]
**Please ensure the feature or the change you're suggesting isn't out of the scope of this project. In most cases, only bug fixes, beneficial MM3D change reversals or QoL improvements will be accepted.**

**Description**
I'd like to have swapped R-ZR and L-ZL

**Additional context**
When using Circle Pad Pro on 3DS the Z triggers are bigger, lower, and mimic triggers in normal controllers, they are more natural as main triggers.

**Comment by leoetlino** [comment]
Unfortunately I can't make this change because not everyone has the Z triggers, and it'd be difficult (AFAICT) to detect whether an user has the additional buttons and swap them dynamically. In my opinion it'd also be baffling if ZL and R/ZR were swapped just by having the Circle Pad Pro attached as it normally only behaves as an addon.
